services:
  mongo-version-db:
    image: mongo
    container_name: mongo-version-db
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - wforce-network

  wforce-version-control:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - wforce-network

networks:
  wforce-network:
    driver: bridge
  