services:
  wforce-mongo-db:
    image: mongo
    container_name: wforce-mongo-db
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - wforce-network

  wforce-jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - 3003:8080
    networks:
      - wforce-network

  wforce-version-control:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - wforce-network

networks:
  wforce-network:
    driver: bridge
  